### PR TITLE
Initial conversion to Gradle

### PR DESCRIPTION
**Pull request by andrzejressel**
Unfortunatelly app uses some removed GDrive api, so it must be fixed before merging. Unfortunatelly I haven't used these apis so I can't help with that.

### CODE REVIEW

**Comment by giuliohome** [comment]
Hi @jereksel thank you very much for your help!
I've received your comment just know, I still have to look at your changes.
In the meantime, why do you say that the GDrive apis are "removed"? I am using them without issues, but I will try to fix any issues if you point me to what's not working.
Thank you again for your valuable time!

**Comment by giuliohome** [comment]
@jereksel Sorry, aside from the GDrive, I'm not an expert of git: what should I do: merging the pull request and then? I won't be able to open the project in eclipse but which IDE should I use? I guess I have to rewrite all this old code for Kotlin, right?
Thanks, your work here is much appreciated

**Comment by andrzejressel** [comment]
I think you were using very old google libraries. Underlying implementation of them is the same (that's why it's still working) but developer api has changed.

You should Android Studio for IDE: https://developer.android.com/studio/index.html. Rewriting to Kotlin is not mandatory.

**Comment by giuliohome** [comment]
@jereksel Excellent, great! I'm going to download Android Studio, so I will be able to learn and practice some Kotlin and FP on Android. This code is very old and the latest updates are missing, plus I want to implement the new Bookmarks feature... I'll try to keep this updated. Thanks a lot

**Pull request merged**
